[window]
opacity = 0.8

[window.dimensions]
columns = 0
lines = 0

[font.normal]
family = "firacode"
style = "Regular"

[shell]
program = "/usr/bin/zsh"

[window.padding]
y = 8
x = 8

[colors.bright]
black = "#565656"
blue = "#49a4f8"
cyan = "#99faf2"
green = "#c0e17d"
magenta = "#a47de9"
red = "#ec5357"
white = "#ffffff"
yellow = "#f9da6a"

[colors.normal]
black = "#2e2e2e"
blue = "#47a0f3"
cyan = "#64dbed"
green = "#abe047"
magenta = "#7b5cb0"
red = "#eb4129"
white = "#e5e9f0"
yellow = "#f6c744"

[colors.primary]
background = "#0f1117"
foreground = "#fffbf6"

